# Generated by Django 5.2.8 on 2026-10-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0027_alter_circuit_options_alter_constructor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='location'),
        ),
    ]
